UPDATE Chemical
SET image = 'https://as2.ftcdn.net/v2/jpg/04/75/27/03/1000_F_475270308_IhnWTqXjtA2d0X64VpYC0DFU2miIdGNY.jpg'
WHERE chemical_id = 1;


UPDATE Chemical
SET image = 'https://static.vecteezy.com/system/resources/previews/026/231/720/original/amoxicillin-antibiotic-chemical-formula-and-composition-concept-structural-medical-drug-isolated-on-white-background-illustration-vector.jpg'
WHERE chemical_id = 2;


UPDATE Chemical
SET image = 'https://www.alphalabs.co.uk/media/catalog/product/0/3/039-01335-1.jpg'
WHERE chemical_id = 3;

UPDATE Chemical
SET image = 'https://5.imimg.com/data5/SELLER/Default/2022/11/XD/PE/TL/13066948/500-ml-povidone-iodine-microbicidal-solution-i-p-500x500.jpg'
WHERE chemical_id = 4;

UPDATE Chemical
SET image = 'https://t3.ftcdn.net/jpg/03/95/48/32/360_F_395483249_FhBVHEofkns2wEcXFi38ZgCD7WYHSYbX.jpg'
WHERE chemical_id = 5;

UPDATE Chemical
SET image = 'https://www.himedialabs.com/media/catalog/product/cache/877ab4ac479bafc7781763a993c9e527/g/r/grm164-500g_1.png'
WHERE chemical_id = 6;

UPDATE Chemical
SET image = 'https://5.imimg.com/data5/SELLER/Default/2020/12/XG/CN/JW/27969458/chlorohexiden-mouthwash-500x500.JPG'
WHERE chemical_id = 7;


UPDATE Chemical
SET image = 'https://www.shutterstock.com/image-vector/methylphenidate-mp-mph-molecule-central-260nw-2060990453.jpg'
WHERE chemical_id = 8;

UPDATE Chemical
SET image = 'https://media.istockphoto.com/id/1207907373/vector/ribavirin-tribavirin-c8h12n4o5-molecule-it-is-antiviral-medication-for-treatment-rsv.jpg?s=612x612&w=0&k=20&c=BN0_jGG3hST-vcltQgbtKRLzK2uXiITMWUzlFgCutfw='
WHERE chemical_id = 9;


