INSERT INTO MedicineChemical (medicine_id, chemical_id, purpose)
VALUES
    (1, 1, 'Active Ingredient'),  -- Napa Extend - Paracetamol
    (2, 1, 'Active Ingredient'),  -- Ace - Paracetamol
    (3, 2, 'Active Ingredient'),  -- Fluclox - Amoxicillin
    (4, 3, 'Active Ingredient'),  -- Systear - Carboxymethylcellulose Sodium
    (5, 4, 'Active Ingredient'),  -- Optimox - Povidone-Iodine
    (6, 5, 'Active Ingredient'),  -- Orsaline-N - ORS
    (7, 6, 'Active Ingredient'),  -- Savlon - Cetrimide
    (8, 4, 'Active Ingredient'),  -- Savlon - Chlorhexidine Gluconate
    (9, 8, 'Active Ingredient'), -- Methyphen - Methylphenidate
    (10, 9, 'Active Ingredient');
